ports:
    - port: 8080
      onOpen: open-browser
tasks:
    - command: >
        npm i jest@24.8.0 -g;
        npm i breathecode-cli -g;
        bc run:exercises;
        
github:
    prebuilds:
        # enable for the master/default branch (defaults to true)
        master: true
        # enable for pull requests coming from this repo (defaults to true)
        pullRequests: false
        # add a "Review in Gitpod" button as a comment to pull requests (defaults to true)
        addComment: false
